version: "3.1"

services:
  db:
    image: postgres:12.4-alpine
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_DB: "${PG_DB}"

  adminer:
    image: adminer
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - db
