// Provides automatically all queries that can be used for api
// integration tests, using graphql documents generated by codegen

import { print } from "graphql/language/printer"
import { JestGlobal } from "jest/types.d"
import * as generated from "../../../../generated/operations"
import { GraphqlTestClient } from "./client/GraphqlTestClient"

declare const global: JestGlobal
const { prisma } = global

const client = GraphqlTestClient({ prisma })

const documents = Object.entries(generated).filter(([k, v]) =>
  k.includes("Document")
)

const queries = documents.map(([k, v]: [k: string, v: any]) => [
  k.replace("Document", "").toLowerCase(),
  (variables?: any) => client(print(v), variables),
])

export default Object.fromEntries(queries)
