export const fakeUsersData = [
  { name: "Zella Hartmann", email: "zella.hartmann@example.com" },
  { name: "Kathryn Rath", email: "kathryn.rath@example.com" },
  { name: "Esther Torp", email: "esther.torp@example.com" },
  {
    name: "Domenica Jaskolski",
    email: "domenica.jaskolski@example.com",
  },
  { name: "Katelyn Windler", email: "katelyn.windler@example.com" },
  { name: "Ben Blanda", email: "ben.blanda@example.com" },
  { name: "Abby Hintz", email: "abby.hintz@example.com" },
  { name: "Rodrigo Purdy", email: "rodrigo.purdy@example.com" },
  { name: "Cecelia Ward", email: "cecelia.ward@example.com" },
  { name: "Laverne Erdman", email: "laverne.erdman@example.com" },
  { name: "Jaclyn Krajcik", email: "jaclyn.krajcik@example.com" },
  { name: "Lorenz Bauch", email: "lorenz.bauch@example.com" },
  { name: "Derek Powlowski", email: "derek.powlowski@example.com" },
  { name: "Nicole Reilly", email: "nicole.reilly@example.com" },
  { name: "Brenda Vandervort", email: "brenda.vandervort@example.com" },
  { name: "Grayson Casper", email: "grayson.casper@example.com" },
  { name: "Richmond Bradtke", email: "richmond.bradtke@example.com" },
  { name: "Waino Marvin", email: "waino.marvin@example.com" },
  { name: "Allen Lindgren", email: "allen.lindgren@example.com" },
  { name: "Jane Bergstrom", email: "jane.bergstrom@example.com" },
  { name: "Sim Trantow", email: "sim.trantow@example.com" },
  { name: "Michael Tromp", email: "michael.tromp@example.com" },
  { name: "Mauricio Bernier", email: "mauricio.bernier@example.com" },
  { name: "Etha Pagac", email: "etha.pagac@example.com" },
  { name: "Maxwell Watsica", email: "maxwell.watsica@example.com" },
  { name: "Audra Gutkowski", email: "audra.gutkowski@example.com" },
  { name: "Rosalee Wyman", email: "rosalee.wyman@example.com" },
  { name: "Oscar Rath", email: "oscar.rath@example.com" },
  { name: "Lamar Kuphal", email: "lamar.kuphal@example.com" },
  { name: "Alexander Welch", email: "alexander.welch@example.com" },
  { name: "Naomi Corwin", email: "naomi.corwin@example.com" },
  { name: "Liana Kulas", email: "liana.kulas@example.com" },
  { name: "Linwood Bruen", email: "linwood.bruen@example.com" },
  { name: "John O'Connell", email: "john.o'connell@example.com" },
  { name: "Austen Fahey", email: "austen.fahey@example.com" },
  { name: "Margaretta Adams", email: "margaretta.adams@example.com" },
  { name: "Brant Upton", email: "brant.upton@example.com" },
  { name: "Shawna O'Keefe", email: "shawna.o'keefe@example.com" },
  {
    name: "Joaquin Satterfield",
    email: "joaquin.satterfield@example.com",
  },
  { name: "Barton Bayer", email: "barton.bayer@example.com" },
  { name: "Armand Greenholt", email: "armand.greenholt@example.com" },
  { name: "Lorenz Langosh", email: "lorenz.langosh@example.com" },
  { name: "Neha Lakin", email: "neha.lakin@example.com" },
  { name: "Mariane O'Conner", email: "mariane.o'conner@example.com" },
  { name: "Arvilla Romaguera", email: "arvilla.romaguera@example.com" },
  { name: "Hope Swaniawski", email: "hope.swaniawski@example.com" },
  { name: "Trey Crist", email: "trey.crist@example.com" },
  { name: "Reynold Schroeder", email: "reynold.schroeder@example.com" },
  { name: "Anjali Rath", email: "anjali.rath@example.com" },
  { name: "Lonnie Rolfson", email: "lonnie.rolfson@example.com" },
  { name: "Leatha Kovacek", email: "leatha.kovacek@example.com" },
  { name: "Verona Dach", email: "verona.dach@example.com" },
  { name: "Adolph Ratke", email: "adolph.ratke@example.com" },
  { name: "Victor Shanahan", email: "victor.shanahan@example.com" },
  { name: "Eliezer Upton", email: "eliezer.upton@example.com" },
  { name: "Zelma Hand", email: "zelma.hand@example.com" },
  { name: "Jeremy Moore", email: "jeremy.moore@example.com" },
  {
    name: "Christelle Monahan",
    email: "christelle.monahan@example.com",
  },
  { name: "Lazaro Lindgren", email: "lazaro.lindgren@example.com" },
  { name: "Ona Stokes", email: "ona.stokes@example.com" },
  { name: "Bessie Aufderhar", email: "bessie.aufderhar@example.com" },
  { name: "Mariam Bednar", email: "mariam.bednar@example.com" },
  { name: "Javonte Hessel", email: "javonte.hessel@example.com" },
  { name: "Curt Fritsch", email: "curt.fritsch@example.com" },
  { name: "Pablo Kuhic", email: "pablo.kuhic@example.com" },
  { name: "Viva Pagac", email: "viva.pagac@example.com" },
  { name: "Armand Morissette", email: "armand.morissette@example.com" },
  {
    name: "Taylor Christiansen",
    email: "taylor.christiansen@example.com",
  },
  { name: "Keegan Hane", email: "keegan.hane@example.com" },
  { name: "Malvina Simonis", email: "malvina.simonis@example.com" },
  { name: "Alejandrin Stehr", email: "alejandrin.stehr@example.com" },
  { name: "Jarrell Bradtke", email: "jarrell.bradtke@example.com" },
  { name: "Cameron Adams", email: "cameron.adams@example.com" },
  { name: "Dion Stark", email: "dion.stark@example.com" },
  { name: "Brielle Harber", email: "brielle.harber@example.com" },
  { name: "Morton Goodwin", email: "morton.goodwin@example.com" },
  { name: "Judson O'Kon", email: "judson.o'kon@example.com" },
  { name: "Glenna Little", email: "glenna.little@example.com" },
  { name: "Lorine Ebert", email: "lorine.ebert@example.com" },
  { name: "Casimer Kihn", email: "casimer.kihn@example.com" },
  { name: "Tamia Prohaska", email: "tamia.prohaska@example.com" },
  { name: "Silas Green", email: "silas.green@example.com" },
  { name: "Lorena Green", email: "lorena.green@example.com" },
  { name: "Jillian Zboncak", email: "jillian.zboncak@example.com" },
  { name: "Susana Spinka", email: "susana.spinka@example.com" },
  { name: "Adolf Bode", email: "adolf.bode@example.com" },
  { name: "Reginald Gibson", email: "reginald.gibson@example.com" },
  { name: "Reba Buckridge", email: "reba.buckridge@example.com" },
  { name: "Phyllis Miller", email: "phyllis.miller@example.com" },
  { name: "Selmer Kohler", email: "selmer.kohler@example.com" },
]
