name: Test
on: pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: node:12.13.0

    services:
      postgres:
        image: postgres:12.4-alpine
        ports:
          - 5432:5432

        env:
          POSTGRES_PASSWORD: ci
          POSTGRES_USER: ci
          POSTGRES_DB: ci
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn install --frozen-lockfile
      - run: yarn test:ci
        env:
          PG_URL: postgresql://ci:ci@postgres:5432/ci?schema=public
          COOKIE_SESSION_KEY1: SECRET_SECRET_SECRET_SECRET
          COOKIE_SESSION_KEY2: SECRET_SECRET_SECRET_SECRET
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_UPLOAD_SECRET }}
